resources:
  - name: repo_1_docker_build_push
    type: GitRepo
    configuration:
      gitProvider: manishas_github   # replace with your integration
      path: manishas-jfrog/jfrog-pipelines-docker-build-push    # replace with your repository name
      branches:
        include: master

  - name: build_info_1_docker_build_push
    type: BuildInfo
    configuration:
      sourceArtifactory: demoArt
      buildName: svc_build
      buildNumber: 1

pipelines:
  - name: pipeline_docker_build_push
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: pipe-master.jfrog.info:8082/docker-local/alpine37
          dockerImageTag: ${run_number}
          inputResources:
            - name: repo_1_docker_build_push
          integrations:
            - name: demoArt

      - name: docker_push
        type: DockerPush
        configuration:
          targetRepository: docker-local
          integrations:
            - name: demoArt
          inputSteps:
            - name: docker_build

      - name: publish_build_info
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: docker_push
          outputResources:
            - name: build_info_1_docker_build_push
